### ISSUE TITLE
Xcode Beta3 Run Error

### ISSUE THREAD

**Issue by josercc** [helje5/AvocadoToast#2]
dyld: Symbol not found: _$s7Combine11SubscribersO4SinkCy_xq_GAA11CancellableAAMc
  Referenced from: /Users/zhangxing/Library/Developer/Xcode/DerivedData/AvocadoToast-datvuvgklmwxfpfatmaywgsuffse/Build/Products/Debug/AvocadoToast.app/Contents/MacOS/AvocadoToast
  Expected in: /System/Library/Frameworks/Combine.framework/Versions/A/Combine
 in /Users/zhangxing/Library/Developer/Xcode/DerivedData/AvocadoToast-datvuvgklmwxfpfatmaywgsuffse/Build/Products/Debug/AvocadoToast.app/Contents/MacOS/AvocadoToast

> The reason is that I have multiple xcodes

**Comment by helje5** [comment]
You are trying to run xcode b3 on catalina b1 or 2, that doesn’t work

**Comment by josercc** [comment]
@helje5 MacOS10.15 Bate1

```
10.15 Beta (19A471t)
```
